// ðŸ§ª ExercÃ­cio 2 â€“ Erro condicional com estado
// ðŸŽ¯ Objetivo:
// Criar um componente que sÃ³ lanÃ§a erro ao atingir 5 cliques, para treinar a lÃ³gica de erro condicional com useState.

// âœ… Regras:
// Crie um componente chamado ContadorPerigoso.

// Ao clicar no botÃ£o, o contador soma 1 (useState).

// Se o contador chegar a 5, deve lanÃ§ar throw new Error("O contador bugou ao chegar em 5!").

// Use ErrorBoundary para capturar esse erro e mostrar o ErrorFallback.

// O Fallback deve exibir a mensagem de erro e um botÃ£o "Tentar novamente" que reseta tudo.

// ðŸ’¡ Dicas:
// O erro precisa estar no corpo do componente, para ser capturado pelo ErrorBoundary.

// Use resetErrorBoundary no botÃ£o do Fallback para resetar.

// Deixe o contador visÃ­vel na tela antes de dar erro.


import { ErrorBoundary } from 'react-error-boundary'
import ContadorPerigoso from './errorBoundary/parte02/exercicio02/ContadorPerigoso'
import ErrorFallback from './errorBoundary/parte02/exercicio02/ErrorFallBack'

const App = () => {
  return (
    <div>
      <ErrorBoundary FallbackComponent={ErrorFallback}>
        <ContadorPerigoso />
      </ErrorBoundary>
    </div>
  )
}

export default App
